### ISSUE TITLE
Is this library supported?

### ISSUE THREAD

**Issue by mnach** [jpadilla/django-rest-framework-xml#28]
Hi folks!

It turns out that I need to integrate xml-protocol to existed API wroten with DRF.
Unfortunately, this library fails with DRF 3.7+, used by API.

> AttributeError: 'XMLParser' object has no attribute 'charset'

Can I contribute to this library? How to do so?

**Comment by mnach** [comment]
I had a mistake, this library actually works with DRF 3.7 on Django 1.11. Sorry.
